### ISSUE TITLE
Update Parts List Links

### ISSUE THREAD

**Issue by anelson425** [hevnsnt/SecKCESP8266#1]
I was looking at the parts list and the URLs listed appear to be items directly from your shopping cart.

It looks like the WeMos board could/should be this link: https://www.aliexpress.com/item/ESP8266-ESP12-ESP-12-WeMos-D1-Mini-WIFI-Dev-Kit-Development-Board-NodeMCU-Lua/32653918483.html

It looks like the buzzer could/should be this link: https://www.aliexpress.com/item/10pcs-5V-Mini-Magnetic-Active-Buzzer-Alarm-Ringer-Black/32303976047.html

**Comment by hevnsnt** [comment]
Updated Readme, closing issue.  (thanks for the find!)
